# Generated by Django 2.1.8 on 2019-08-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='image',
            field=models.ImageField(upload_to='static/goods', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='image',
            field=models.ImageField(upload_to='static/type', verbose_name='商品类型图片'),
        ),
    ]
